# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wonderful-babbage
spec:
  selector:
    app: wonderful-babbage
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8081  # Port where your application is running inside the pod
  type: LoadBalancer
